// <auto-generated />
using System;
using HyesooProj.Infrastructure.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HyesooProj.Infrastructure.Migrations
{
    [DbContext(typeof(HyesooProjDbContext))]
    [Migration("20190827034542_add-daily")]
    partial class adddaily
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("HyesooProj.Infrastructure.Model.DailyFootPrint", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("DailyFootPrint");
                });

            modelBuilder.Entity("HyesooProj.Infrastructure.Model.FootPrint", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DailyId");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("DailyId");

                    b.ToTable("FootPrints");
                });

            modelBuilder.Entity("HyesooProj.Infrastructure.Model.FootPrint", b =>
                {
                    b.HasOne("HyesooProj.Infrastructure.Model.DailyFootPrint", "Daily")
                        .WithMany()
                        .HasForeignKey("DailyId");
                });
#pragma warning restore 612, 618
        }
    }
}
